employeeId : 501
firstName : Dinesh Vishnu Kumar
lastName : Chandrasekaran
email : d@k.com
phoneNumber : 3434534543534
hireDate : 13/01/2021
jobID : 123
salary : 345.67
commissionPct : 345.89
managerId : 123
departmentId : 209